[nfs]
172.31.89.144 ansible_ssh_user=ec2-user

[webservers]
172.31.80.203 ansible_ssh_user=ec2-user
54.175.45.234 ansible_ssh_user=ec2-user

[db]
172.31.85.28 ansible_ssh_user=ec2-user 

[lb]
172.31.82.18 ansible_ssh_user=ubuntu
